syntax = "proto3";

option java_package = "com.yourssu.soomsil.usaint.proto";
option java_multiple_files = true;

message ChapelDataProto {
  int32 year = 1;        // 연도
  string semester = 2;        // 학기
  int64 division = 3;        // 분반
  string chapelTime = 4;              // 채플 시간
  string chapelRoom = 5;              // 채플 강의실
  int32 floorLevel = 6;              // 층수
  string seatNumber = 7;              // 좌석
  int32 absenceTime = 8;              // 결석일수
  string result = 9;        // 성적
}