syntax = "proto3";

option java_package = "com.yourssu.soomsil.usaint.proto";
option java_multiple_files = true;

message StudentInformation {
  /**
   * [dev.eatsteak.rusaint.core.GraduationStudent]
   */
  string id = 1;                // 학번
  string name = 2;              // 이름
  int32 grade = 3;              // 학년
  int32 semester = 4;           // 이수학기 (ex: 7)
  string status = 5;            // 학적 상태 (재학 or 휴학)
  int32 applyYear = 6;          // 입학년도
  string applyType = 7;         // 입학유형 (ex: 신입학)
  string department = 8;        // 소속 (ex: IT대학)
  repeated string majors = 9;   // 제1전공 ~ 제4전공
  float graduationPoints = 10;  // 졸업학점
  float completedPoints = 11;   // 인정학점

  /**
   * [dev.eatsteak.rusaint.core.GradeSummary]
   *
   * help me:
   * - 학적부와 증명의 차이점?
   * - 졸업사정표의 인정학점과 학적부 취득학점의 차이점?
   */
  float attemptedCredits = 12;  // 학적부 신청학점
  float earnedCredits = 13;     // 학적부 취득학점
  float gradePointsSum = 14;    // 학적부 평점계
  float gradePointsAverage = 15;// 학적부 평점평균
  float arithmeticMean = 16;    // 학적부 산술평균
  float pfEarnedCredits = 17;   // 학적부 P/F학점
}
