syntax = "proto3";

option java_package = "com.yourssu.soomsil.usaint.proto";
option java_multiple_files = true;

message StudentInformation {
  /**
   * [dev.eatsteak.rusaint.core.GraduationStudent]
   */
  string id = 1;                // 학번
  string name = 2;              // 이름
  int32 grade = 3;              // 학년
  int32 semester = 4;           // 이수학기 (ex: 7)
  string status = 5;            // 학적 상태 (재학 or 휴학)
  int32 apply_year = 6;         // 입학년도
  string apply_type = 7;        // 입학유형 (ex: 신입학)
  string department = 8;        // 소속 (ex: IT대학)
  repeated string majors = 9;  // 제1전공 ~ 제4전공
}
