package com.yourssu.soomsil.usaint.screen.home.model

object SeatData {
    val floor1 = mapOf(
        "A" to SeatInfo(
            seatList = listOf(
                (1..5).toList(),
                (1..6).toList(),
                (1..7).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..5).toList(),
            ),
            spaceIdx = 7,
            frontAlignment = SeatAlignment.RIGHT,
            backAlignment = SeatAlignment.LEFT,
        ),
        "B" to SeatInfo(
            seatList = listOf(
                (1..6).toList(),
                (1..6).toList(),
                (1..6).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..3).toList(),
            ),
            spaceIdx = 7,
            frontAlignment = SeatAlignment.RIGHT,
            backAlignment = SeatAlignment.LEFT,
        ),
        "C" to SeatInfo(
            seatList = listOf(
                (1..9).toList(),
                (1..10).toList(),
                (1..10).toList(),
                (1..10).toList(),
                (1..10).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
                (1..11).toList(),
            ),
            spaceIdx = 7,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.CENTER,
        ),
        "D" to SeatInfo(
            seatList = listOf(
                (1..6).toList(),
                (1..6).toList(),
                (1..6).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
            ),
            spaceIdx = 7,
            frontAlignment = SeatAlignment.LEFT,
            backAlignment = SeatAlignment.CENTER,
        ),
        "E" to SeatInfo(
            seatList = listOf(
                (1..5).toList(),
                (1..6).toList(),
                (1..7).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..5).toList(),
            ),
            spaceIdx = 7,
            frontAlignment = SeatAlignment.LEFT,
            backAlignment = SeatAlignment.RIGHT,
        )
    )

    val floor2 = mapOf(
        "F" to SeatInfo(
            seatList = listOf(
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..6).toList(),
                (1..5).toList(),
            ),
            spaceIdx = 6,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.LEFT,
            additionalIdx = 13,
        ),
        "G" to SeatInfo(
            seatList = listOf(
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..6).toList(),
                (1..6).toList(),
            ),
            spaceIdx = 6,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.LEFT,
        ),
        "H" to SeatInfo(
            seatList = listOf(
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
                (1..9).toList(),
            ),
            spaceIdx = 6,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.CENTER,
        ),
        "I" to SeatInfo(
            seatList = listOf(
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
                (1..7).toList(),
            ),
            spaceIdx = 6,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.CENTER,
        ),
        "J" to SeatInfo(
            seatList = listOf(
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..3).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..8).toList(),
                (1..6).toList(),
                (1..5).toList(),
            ),
            spaceIdx = 6,
            frontAlignment = SeatAlignment.CENTER,
            backAlignment = SeatAlignment.RIGHT,
            additionalIdx = 13,
        ),
    )
}

data class SeatInfo(
    val seatList: List<List<Int>>,
    val spaceIdx: Int,
    val frontAlignment: SeatAlignment,
    val backAlignment: SeatAlignment,
    val additionalIdx: Int? = null,
)

data class SeatId(
    val sector: String,
    val row: Int,
    val col: Int,
) {
    val id: String = "$sector-$row-$col"
}

enum class SeatAlignment { LEFT, CENTER, RIGHT }
enum class ZoomLevel { LEVEL2, LEVEL1, LEVEL0 }